### ISSUE TITLE
How to delete quotes when tag message has Multiple lines

### ISSUE THREAD

**Issue by miyouzi** [ericcornelissen/git-tag-annotation-action#23]
Hi, thank you for your project, it's helpful ! And I have a little question.

My action yml below:

```yaml

......

- name: Get tag message
      id: tag_data
      uses: ericcornelissen/git-tag-annotation-action@v1

......

- name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: "${{ env.RELEASE_TITLE }}"
        body: |
          ${{ steps.tag_data.outputs.git-tag-annotation }}
```

Then I found the release body has quotes at the beginning and ending. How to delete it ?

![XBSJ(KN$51N(TSI)DEW61LK](https://user-images.githubusercontent.com/24269465/127107376-a4dc8050-c703-43ba-9feb-8c085b1a809f.png)

The whole yml file is at https://github.com/miyouzi/aniGamerPlus/blob/master/.github/workflows/Release-build.yml
